#!/bin/bash

# This script is slow if run with 0 parallelism.
# However unbounded parallelism is never the answer.
# Working out the optimal parallelism,
# for any given system is complicated.
# Thefore, running each type in the background is a nice organization.
# It gets us way faster and solves the problem.
# By putting each type into it's own script
# this also preverves order.

SOURCEDIR=$( dirname -- "$0"; )

chmod +x $SOURCEDIR/load-employees $SOURCEDIR/load-meetings $SOURCEDIR/load-projects $SOURCEDIR/load-reservations $SOURCEDIR/load-tickets $SOURCEDIR/load-timecards

# Put employees
$SOURCEDIR/load-employees "$@" &

# # Put meetings
$SOURCEDIR/load-meetings "$@" &

# # Put projects
$SOURCEDIR/load-projects "$@" &

# # Put reservations
$SOURCEDIR/load-reservations "$@" &

# # Put tickets
$SOURCEDIR/load-tickets "$@" &

# # Put timecards
$SOURCEDIR/load-timecards "$@" &

wait
