#!/bin/bash

# Put projects
./employee-portal put-project $1 -N 1 -s Pending -S 2022-11-01 -P "Turbo Crypto" -t 2024-01-01
./employee-portal put-project $1 -N 2 -s Active  -S 2022-07-04 -P "Scan Beacons" -t 2023-02-27
./employee-portal put-project $1 -N 3 -s Active  -S 2022-08-05 -P "Gazelle"      -t 2023-03-27
./employee-portal put-project $1 -N 4 -s Done    -S 2020-03-03 -P "S3EC"         -t 2021-09-05
